module.exports = {
	// 单独页面打开
	singleView: ['/login'],

	// 隐藏左侧导航
	hideLeftView: ['/authority'],


	// 表单布局
	formItemLayout: {
		labelCol: {
			xs: { span: 8 },
			sm: { span: 10 },
		},
		wrapperCol: {
			xs: { span: 16 },
			sm: { span: 14 },
		},
	},

	datalist: [
		{
			name: '用户管理',
			icon: 'team',
			modelpage: '/userSetting',
			id: 1
		},
		{
			name: '角色管理',
			icon: 'user',
			modelpage: '/roleSetting',
			id: 4
		},
		{
			name: '文件上传',
			icon: 'upload',
			modelpage: '/upload',
			id: 2
		},
		{
			name: '菜单管理',
			icon: 'tuisong',
			modelpage: '/authMenu',
			id: 3
		},
		// {
		// 	name: '系统管理',
		// 	icon: 'appstore-o',
		// 	modelpage: '',
		// 	id: 4,
		// 	children: [
		// 		{
		// 			name: '日志管理',
		// 			icon: 'calendar',
		// 			modelpage: '',
		// 			id: 5,
        //             children: [
		// 				{
		// 					name: '删除日志',
		// 					icon: '',
		// 					modelpage: '/system/logs/deleteLogs',
		// 				}
		// 			]
		// 		}
		// 	]
		// }
	]

	// 模拟接口数据
	// "datalist": [
	// 	{
	// 	    "checked": "",
	// 	    "children": [
	// 	    {
	// 	        "checked": "true",
	// 	        "children": [
	// 	        {
	// 	            "checked": "true",
	// 	            "children": [
	// 	            {
	// 	                "checked": "true",
	// 	                "children": [],
	// 	                "cname": "赚钱任务总览",
	// 	                "createdate": "",
	// 	                "creator": "",
	// 	                "flag": 0,
	// 	                "icon": "zongrenwu",
	// 	                "id": 12826,
	// 	                "modelpage": "/dftt/dftt-zq/task",
	// 	                "pid": 12825,
	// 	                "proid": 7,
	// 	                "realname": "",
	// 	                "redirect": "",
	// 	                "rel": "",
	// 	                "sortid": 1,
	// 	                "updatedate": "",
	// 	                "updator": ""
	// 	            },
	// 	            {
	// 	                "checked": "",
	// 	                "children": [
	// 	                {
	// 	                    "checked": "",
	// 	                    "children": [],
	// 	                    "cname": "阅读文章",
	// 	                    "createdate": "",
	// 	                    "creator": "",
	// 	                    "flag": 0,
	// 	                    "icon": "tongji",
	// 	                    "id": 12829,
	// 	                    "modelpage": "/dftt/dftt-zq/read-article",
	// 	                    "pid": 120037,
	// 	                    "proid": 7,
	// 	                    "realname": "",
	// 	                    "redirect": "",
	// 	                    "rel": "",
	// 	                    "sortid": 2,
	// 	                    "updatedate": "",
	// 	                    "updator": ""
	// 	                },
	// 	                {
	// 	                    "checked": "",
	// 	                    "children": [],
	// 	                    "cname": "阅读文章次数",
	// 	                    "createdate": "",
	// 	                    "creator": "",
	// 	                    "flag": 0,
	// 	                    "icon": "tongji",
	// 	                    "id": 120029,
	// 	                    "modelpage": "/dftt/dftt-zq/read-count",
	// 	                    "pid": 120037,
	// 	                    "proid": 7,
	// 	                    "realname": "",
	// 	                    "redirect": "",
	// 	                    "rel": "",
	// 	                    "sortid": 2.1,
	// 	                    "updatedate": "",
	// 	                    "updator": ""
	// 	                }],
	// 	                "cname": "阅读文章",
	// 	                "createdate": "",
	// 	                "creator": "",
	// 	                "flag": 0,
	// 	                "icon": "yuedu",
	// 	                "id": 120037,
	// 	                "modelpage": "/dftt/dftt-zq/read",
	// 	                "pid": 12825,
	// 	                "proid": 7,
	// 	                "realname": "",
	// 	                "redirect": "",
	// 	                "rel": "",
	// 	                "sortid": 2.5,
	// 	                "updatedate": "",
	// 	                "updator": ""
	// 	            },
	// 	            {
	// 	                "checked": "",
	// 	                "children": [],
	// 	                "cname": "阅读推送文章",
	// 	                "createdate": "",
	// 	                "creator": "",
	// 	                "flag": 0,
	// 	                "icon": "tuisong",
	// 	                "id": 12830,
	// 	                "modelpage": "/dftt/dftt-zq/push",
	// 	                "pid": 12825,
	// 	                "proid": 7,
	// 	                "realname": "",
	// 	                "redirect": "",
	// 	                "rel": "",
	// 	                "sortid": 3,
	// 	                "updatedate": "",
	// 	                "updator": ""
	// 	            },
	// 	            {
	// 	                "checked": "",
	// 	                "children": [
	// 	                {
	// 	                    "checked": "",
	// 	                    "children": [],
	// 	                    "cname": "分享新闻",
	// 	                    "createdate": "",
	// 	                    "creator": "",
	// 	                    "flag": 0,
	// 	                    "icon": "tongji",
	// 	                    "id": 12827,
	// 	                    "modelpage": "/dftt/dftt-zq/share-news",
	// 	                    "pid": 12876,
	// 	                    "proid": 7,
	// 	                    "realname": "",
	// 	                    "redirect": "",
	// 	                    "rel": "",
	// 	                    "sortid": 1,
	// 	                    "updatedate": "",
	// 	                    "updator": ""
	// 	                },
	// 	                {
	// 	                    "checked": "",
	// 	                    "children": [],
	// 	                    "cname": "分享被阅读",
	// 	                    "createdate": "",
	// 	                    "creator": "",
	// 	                    "flag": 0,
	// 	                    "icon": "tongji",
	// 	                    "id": 12828,
	// 	                    "modelpage": "/dftt/dftt-zq/share-readed",
	// 	                    "pid": 12876,
	// 	                    "proid": 7,
	// 	                    "realname": "",
	// 	                    "redirect": "",
	// 	                    "rel": "",
	// 	                    "sortid": 2,
	// 	                    "updatedate": "",
	// 	                    "updator": ""
	// 	                },
	// 	                {
	// 	                    "checked": "",
	// 	                    "children": [],
	// 	                    "cname": "新闻排行榜",
	// 	                    "createdate": "",
	// 	                    "creator": "",
	// 	                    "flag": 0,
	// 	                    "icon": "tongji",
	// 	                    "id": 121296,
	// 	                    "modelpage": "/dftt/dftt-zq/share-rank",
	// 	                    "pid": 12876,
	// 	                    "proid": 7,
	// 	                    "realname": "",
	// 	                    "redirect": "",
	// 	                    "rel": "",
	// 	                    "sortid": 5,
	// 	                    "updatedate": "",
	// 	                    "updator": ""
	// 	                }],
	// 	                "cname": "分享被阅读",
	// 	                "createdate": "",
	// 	                "creator": "",
	// 	                "flag": 0,
	// 	                "icon": "fenxiang",
	// 	                "id": 12876,
	// 	                "modelpage": "/dftt/dftt-zq/share",
	// 	                "pid": 12825,
	// 	                "proid": 7,
	// 	                "realname": "",
	// 	                "redirect": "0",
	// 	                "rel": "",
	// 	                "sortid": 4,
	// 	                "updatedate": "",
	// 	                "updator": ""
	// 	            },
	// 	            {
	// 	                "checked": "",
	// 	                "children": [
	// 	                {
	// 	                    "checked": "",
	// 	                    "children": [],
	// 	                    "cname": "APP邀请收徒统计",
	// 	                    "createdate": "",
	// 	                    "creator": "",
	// 	                    "flag": 0,
	// 	                    "icon": "tongji",
	// 	                    "id": 12085,
	// 	                    "modelpage": "/dftt/dftt-zq/apprentice-app-count",
	// 	                    "pid": 12874,
	// 	                    "proid": 7,
	// 	                    "realname": "",
	// 	                    "redirect": "",
	// 	                    "rel": "",
	// 	                    "sortid": 1,
	// 	                    "updatedate": "",
	// 	                    "updator": ""
	// 	                },
	// 	                {
	// 	                    "checked": "",
	// 	                    "children": [],
	// 	                    "cname": "APP邀请收徒排行榜",
	// 	                    "createdate": "",
	// 	                    "creator": "",
	// 	                    "flag": 0,
	// 	                    "icon": "tongji",
	// 	                    "id": 12589,
	// 	                    "modelpage": "/dftt/dftt-zq/apprentice-app-rank",
	// 	                    "pid": 12874,
	// 	                    "proid": 7,
	// 	                    "realname": "",
	// 	                    "redirect": "",
	// 	                    "rel": "",
	// 	                    "sortid": 3,
	// 	                    "updatedate": "",
	// 	                    "updator": ""
	// 	                },
	// 	                {
	// 	                    "checked": "",
	// 	                    "children": [],
	// 	                    "cname": "师徒质量监控",
	// 	                    "createdate": "",
	// 	                    "creator": "",
	// 	                    "flag": 0,
	// 	                    "icon": "tongji",
	// 	                    "id": 12879,
	// 	                    "modelpage": "/dftt/dftt-zq/apprentice-quality",
	// 	                    "pid": 12874,
	// 	                    "proid": 7,
	// 	                    "realname": "",
	// 	                    "redirect": "",
	// 	                    "rel": "",
	// 	                    "sortid": 4,
	// 	                    "updatedate": "",
	// 	                    "updator": ""
	// 	                },
	// 	                {
	// 	                    "checked": "",
	// 	                    "children": [],
	// 	                    "cname": "师父数据统计",
	// 	                    "createdate": "",
	// 	                    "creator": "",
	// 	                    "flag": 0,
	// 	                    "icon": "tongji",
	// 	                    "id": 120083,
	// 	                    "modelpage": "/dftt/dftt-zq/apprentice-master",
	// 	                    "pid": 12874,
	// 	                    "proid": 7,
	// 	                    "realname": "",
	// 	                    "redirect": "",
	// 	                    "rel": "",
	// 	                    "sortid": 5,
	// 	                    "updatedate": "",
	// 	                    "updator": ""
	// 	                },
	// 	                {
	// 	                    "checked": "",
	// 	                    "children": [],
	// 	                    "cname": "徒弟数据统计",
	// 	                    "createdate": "",
	// 	                    "creator": "",
	// 	                    "flag": 0,
	// 	                    "icon": "tongji",
	// 	                    "id": 120123,
	// 	                    "modelpage": "/dftt/dftt-zq/apprentice-prentice",
	// 	                    "pid": 12874,
	// 	                    "proid": 7,
	// 	                    "realname": "",
	// 	                    "redirect": "",
	// 	                    "rel": "",
	// 	                    "sortid": 6,
	// 	                    "updatedate": "",
	// 	                    "updator": ""
	// 	                },
	// 	                {
	// 	                    "checked": "",
	// 	                    "children": [],
	// 	                    "cname": "H5邀请",
	// 	                    "createdate": "",
	// 	                    "creator": "",
	// 	                    "flag": 0,
	// 	                    "icon": "tongji",
	// 	                    "id": 120181,
	// 	                    "modelpage": "/dftt/dftt-zq/apprentice-h5-invite",
	// 	                    "pid": 12874,
	// 	                    "proid": 7,
	// 	                    "realname": "",
	// 	                    "redirect": "",
	// 	                    "rel": "",
	// 	                    "sortid": 7,
	// 	                    "updatedate": "",
	// 	                    "updator": ""
	// 	                },
	// 	                {
	// 	                    "checked": "",
	// 	                    "children": [],
	// 	                    "cname": "拼手气拆红包",
	// 	                    "createdate": "",
	// 	                    "creator": "",
	// 	                    "flag": 0,
	// 	                    "icon": "tongji",
	// 	                    "id": 121094,
	// 	                    "modelpage": "/dftt/dftt-zq/apprentice-red",
	// 	                    "pid": 12874,
	// 	                    "proid": 7,
	// 	                    "realname": "",
	// 	                    "redirect": "",
	// 	                    "rel": "",
	// 	                    "sortid": 10,
	// 	                    "updatedate": "",
	// 	                    "updator": ""
	// 	                }],
	// 	                "cname": "师徒活动",
	// 	                "createdate": "",
	// 	                "creator": "",
	// 	                "flag": 0,
	// 	                "icon": "shitu",
	// 	                "id": 12874,
	// 	                "modelpage": "/dftt/dftt-zq/apprentice",
	// 	                "pid": 12825,
	// 	                "proid": 7,
	// 	                "realname": "",
	// 	                "redirect": "1",
	// 	                "rel": "",
	// 	                "sortid": 5,
	// 	                "updatedate": "",
	// 	                "updator": ""
	// 	            },
	// 	            {
	// 	                "checked": "",
	// 	                "children": [
	// 	                {
	// 	                    "checked": "",
	// 	                    "children": [],
	// 	                    "cname": "摇钱树统计",
	// 	                    "createdate": "",
	// 	                    "creator": "",
	// 	                    "flag": 0,
	// 	                    "icon": "tongji",
	// 	                    "id": 12831,
	// 	                    "modelpage": "/dftt/dftt-zq/money-tree-count",
	// 	                    "pid": 12875,
	// 	                    "proid": 7,
	// 	                    "realname": "",
	// 	                    "redirect": "",
	// 	                    "rel": "",
	// 	                    "sortid": 6,
	// 	                    "updatedate": "",
	// 	                    "updator": ""
	// 	                },
	// 	                {
	// 	                    "checked": "",
	// 	                    "children": [],
	// 	                    "cname": "APP摇钱树次数分布",
	// 	                    "createdate": "",
	// 	                    "creator": "",
	// 	                    "flag": 0,
	// 	                    "icon": "tongji",
	// 	                    "id": 12603,
	// 	                    "modelpage": "/dftt/dftt-zq/money-tree-distribute",
	// 	                    "pid": 12875,
	// 	                    "proid": 7,
	// 	                    "realname": "",
	// 	                    "redirect": "",
	// 	                    "rel": "",
	// 	                    "sortid": 7,
	// 	                    "updatedate": "",
	// 	                    "updator": ""
	// 	                }],
	// 	                "cname": "摇钱树活动",
	// 	                "createdate": "",
	// 	                "creator": "",
	// 	                "flag": 0,
	// 	                "icon": "yaoqianshu",
	// 	                "id": 12875,
	// 	                "modelpage": "/dftt/dftt-zq/money",
	// 	                "pid": 12825,
	// 	                "proid": 7,
	// 	                "realname": "",
	// 	                "redirect": "2",
	// 	                "rel": "",
	// 	                "sortid": 6,
	// 	                "updatedate": "",
	// 	                "updator": ""
	// 	            },
	// 	            {
	// 	                "checked": "",
	// 	                "children": [],
	// 	                "cname": "一次性任务奖励",
	// 	                "createdate": "",
	// 	                "creator": "",
	// 	                "flag": 0,
	// 	                "icon": "yicirenwu",
	// 	                "id": 12993,
	// 	                "modelpage": "/dftt/dftt-zq/disposable-reward",
	// 	                "pid": 12825,
	// 	                "proid": 7,
	// 	                "realname": "",
	// 	                "redirect": "",
	// 	                "rel": "",
	// 	                "sortid": 8,
	// 	                "updatedate": "",
	// 	                "updator": ""
	// 	            },
	// 	            {
	// 	                "checked": "",
	// 	                "children": [],
	// 	                "cname": "每日签到",
	// 	                "createdate": "",
	// 	                "creator": "",
	// 	                "flag": 0,
	// 	                "icon": "qiandao",
	// 	                "id": 13013,
	// 	                "modelpage": "/dftt/dftt-zq/sign",
	// 	                "pid": 12825,
	// 	                "proid": 7,
	// 	                "realname": "",
	// 	                "redirect": "",
	// 	                "rel": "",
	// 	                "sortid": 9,
	// 	                "updatedate": "",
	// 	                "updator": ""
	// 	            },
	// 	            {
	// 	                "checked": "",
	// 	                "children": [
	// 	                {
	// 	                    "checked": "",
	// 	                    "children": [],
	// 	                    "cname": "晒收入统计",
	// 	                    "createdate": "",
	// 	                    "creator": "",
	// 	                    "flag": 0,
	// 	                    "icon": "tongji",
	// 	                    "id": 120220,
	// 	                    "modelpage": "/dftt/dftt-zq/daily-show-income",
	// 	                    "pid": 120219,
	// 	                    "proid": 7,
	// 	                    "realname": "",
	// 	                    "redirect": "",
	// 	                    "rel": "",
	// 	                    "sortid": 1,
	// 	                    "updatedate": "",
	// 	                    "updator": ""
	// 	                },
	// 	                {
	// 	                    "checked": "",
	// 	                    "children": [],
	// 	                    "cname": "新闻搜索任务数据",
	// 	                    "createdate": "",
	// 	                    "creator": "",
	// 	                    "flag": 0,
	// 	                    "icon": "tongji",
	// 	                    "id": 121183,
	// 	                    "modelpage": "/dftt/dftt-zq/daily-news-search",
	// 	                    "pid": 120219,
	// 	                    "proid": 7,
	// 	                    "realname": "",
	// 	                    "redirect": "",
	// 	                    "rel": "",
	// 	                    "sortid": 5,
	// 	                    "updatedate": "",
	// 	                    "updator": ""
	// 	                }],
	// 	                "cname": "每日任务",
	// 	                "createdate": "",
	// 	                "creator": "",
	// 	                "flag": 0,
	// 	                "icon": "",
	// 	                "id": 120219,
	// 	                "modelpage": "/dftt/dftt-zq/daily",
	// 	                "pid": 12825,
	// 	                "proid": 7,
	// 	                "realname": "",
	// 	                "redirect": "",
	// 	                "rel": "",
	// 	                "sortid": 10,
	// 	                "updatedate": "",
	// 	                "updator": ""
	// 	            },
	// 	            {
	// 	                "checked": "",
	// 	                "children": [
	// 	                {
	// 	                    "checked": "",
	// 	                    "children": [],
	// 	                    "cname": "唤醒徒儿",
	// 	                    "createdate": "",
	// 	                    "creator": "",
	// 	                    "flag": 0,
	// 	                    "icon": "tongji",
	// 	                    "id": 120460,
	// 	                    "modelpage": "/dftt/dftt-zq/awaken-prentice",
	// 	                    "pid": 120459,
	// 	                    "proid": 7,
	// 	                    "realname": "",
	// 	                    "redirect": "",
	// 	                    "rel": "",
	// 	                    "sortid": 1,
	// 	                    "updatedate": "",
	// 	                    "updator": ""
	// 	                },
	// 	                {
	// 	                    "checked": "",
	// 	                    "children": [],
	// 	                    "cname": "唤醒好友",
	// 	                    "createdate": "",
	// 	                    "creator": "",
	// 	                    "flag": 0,
	// 	                    "icon": "tongji",
	// 	                    "id": 120518,
	// 	                    "modelpage": "/dftt/dftt-zq/awaken-friend",
	// 	                    "pid": 120459,
	// 	                    "proid": 7,
	// 	                    "realname": "",
	// 	                    "redirect": "",
	// 	                    "rel": "",
	// 	                    "sortid": 2,
	// 	                    "updatedate": "",
	// 	                    "updator": ""
	// 	                }],
	// 	                "cname": "唤醒",
	// 	                "createdate": "",
	// 	                "creator": "",
	// 	                "flag": 0,
	// 	                "icon": "huanxing",
	// 	                "id": 120459,
	// 	                "modelpage": "/dftt/dftt-zq/awaken",
	// 	                "pid": 12825,
	// 	                "proid": 7,
	// 	                "realname": "",
	// 	                "redirect": "",
	// 	                "rel": "",
	// 	                "sortid": 11,
	// 	                "updatedate": "",
	// 	                "updator": ""
	// 	            },
	// 	            {
	// 	                "checked": "",
	// 	                "children": [],
	// 	                "cname": "20点抢红包统计",
	// 	                "createdate": "",
	// 	                "creator": "",
	// 	                "flag": 0,
	// 	                "icon": "hongbao",
	// 	                "id": 121188,
	// 	                "modelpage": "/dftt/dftt-zq/twenty-dian",
	// 	                "pid": 12825,
	// 	                "proid": 7,
	// 	                "realname": "",
	// 	                "redirect": "",
	// 	                "rel": "",
	// 	                "sortid": 12,
	// 	                "updatedate": "",
	// 	                "updator": ""
	// 	            },
	// 	            {
	// 	                "checked": "",
	// 	                "children": [],
	// 	                "cname": "全民答题统计",
	// 	                "createdate": "",
	// 	                "creator": "",
	// 	                "flag": 0,
	// 	                "icon": "dati",
	// 	                "id": 121597,
	// 	                "modelpage": "/dftt/dftt-zq/answer",
	// 	                "pid": 12825,
	// 	                "proid": 7,
	// 	                "realname": "",
	// 	                "redirect": "",
	// 	                "rel": "",
	// 	                "sortid": 12.1,
	// 	                "updatedate": "",
	// 	                "updator": ""
	// 	            },
	// 	            {
	// 	                "checked": "",
	// 	                "children": [],
	// 	                "cname": "排行榜统计",
	// 	                "createdate": "",
	// 	                "creator": "",
	// 	                "flag": 0,
	// 	                "icon": "paihang",
	// 	                "id": 121257,
	// 	                "modelpage": "/dftt/dftt-zq/rank",
	// 	                "pid": 12825,
	// 	                "proid": 7,
	// 	                "realname": "",
	// 	                "redirect": "",
	// 	                "rel": "",
	// 	                "sortid": 13,
	// 	                "updatedate": "",
	// 	                "updator": ""
	// 	            },
	// 	            {
	// 	                "checked": "",
	// 	                "children": [],
	// 	                "cname": "活动会场每日数据 ",
	// 	                "createdate": "",
	// 	                "creator": "",
	// 	                "flag": 0,
	// 	                "icon": "shuju",
	// 	                "id": 121292,
	// 	                "modelpage": "/dftt/dftt-zq/activity",
	// 	                "pid": 12825,
	// 	                "proid": 7,
	// 	                "realname": "",
	// 	                "redirect": "",
	// 	                "rel": "",
	// 	                "sortid": 14,
	// 	                "updatedate": "",
	// 	                "updator": ""
	// 	            }],
	// 	            "cname": "东方头条赚钱",
	// 	            "createdate": "",
	// 	            "creator": "",
	// 	            "flag": 0,
	// 	            "icon": "tongji",
	// 	            "id": 12825,
	// 	            "modelpage": "/dftt/dftt-zq",
	// 	            "pid": 10021,
	// 	            "proid": 7,
	// 	            "realname": "",
	// 	            "redirect": "",
	// 	            "rel": "",
	// 	            "sortid": 0,
	// 	            "updatedate": "",
	// 	            "updator": ""
	// 	        }
    //         ],
	// 	        "cname": "产品",
	// 	        "createdate": "",
	// 	        "creator": "",
	// 	        "flag": 0,
	// 	        "icon": "tongji",
	// 	        "id": 10021,
	// 	        "modelpage": "",
	// 	        "pid": 10002,
	// 	        "proid": 7,
	// 	        "realname": "",
	// 	        "redirect": "",
	// 	        "rel": "",
	// 	        "sortid": 1,
	// 	        "updatedate": "",
	// 	        "updator": ""
	// 		}
	// 	],
	// 	    "cname": "上海嵩恒",
	// 	    "createdate": "",
	// 	    "creator": "",
	// 	    "flag": 0,
	// 	    "icon": "songheng",
	// 	    "id": 10002,
	// 	    "modelpage": "",
	// 	    "pid": 0,
	// 	    "proid": 7,
	// 	    "realname": "",
	// 	    "redirect": "",
	// 	    "rel": "",
	// 	    "sortid": 1,
	// 	    "updatedate": "",
	// 	    "updator": ""
	// 	}
	// ]
	
}